// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using questionnaire.Infrastructure.Data;

namespace questionnaire.Api.Migrations
{
    [DbContext(typeof(questionnaireContext))]
    [Migration("20190127164322_initial")]
    partial class initial
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "2.1.1-rtm-30846")
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("questionnaire.Core.Domains.Abstract.Account", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<bool>("Activated");

                    b.Property<DateTime>("CreatedAt");

                    b.Property<bool>("Deleted");

                    b.Property<string>("Discriminator")
                        .IsRequired();

                    b.Property<string>("Email");

                    b.Property<string>("Name");

                    b.Property<byte[]>("PasswordHash");

                    b.Property<byte[]>("PasswordSalt");

                    b.Property<string>("PhoneNumber");

                    b.Property<string>("Role");

                    b.Property<string>("Surname");

                    b.Property<DateTime>("UpdatedAt");

                    b.HasKey("Id");

                    b.ToTable("Accounts");

                    b.HasDiscriminator<string>("Discriminator").HasValue("Account");
                });

            modelBuilder.Entity("questionnaire.Core.Domains.AccountActivation", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int>("AccountId");

                    b.Property<DateTime>("ActivatedAt");

                    b.Property<Guid>("ActivationKey");

                    b.Property<bool>("Active");

                    b.HasKey("Id");

                    b.HasIndex("AccountId")
                        .IsUnique();

                    b.ToTable("AccountActivation");
                });

            modelBuilder.Entity("questionnaire.Core.Domains.AccountRestoringPassword", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int>("AccountId");

                    b.Property<bool>("Restored");

                    b.Property<DateTime>("RestoredAt");

                    b.Property<Guid>("Token");

                    b.HasKey("Id");

                    b.HasIndex("AccountId")
                        .IsUnique();

                    b.ToTable("AccountRestoringPasswords");
                });

            modelBuilder.Entity("questionnaire.Core.Domains.Certificate", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int>("AccountId");

                    b.Property<DateTime>("DateOfReceived");

                    b.Property<string>("Title");

                    b.HasKey("Id");

                    b.HasIndex("AccountId");

                    b.ToTable("Certificates");
                });

            modelBuilder.Entity("questionnaire.Core.Domains.Course", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int>("AccountId");

                    b.Property<string>("Name");

                    b.HasKey("Id");

                    b.HasIndex("AccountId");

                    b.ToTable("Courses");
                });

            modelBuilder.Entity("questionnaire.Core.Domains.Education", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int>("AccountId");

                    b.Property<string>("Course");

                    b.Property<bool>("Graduated");

                    b.Property<string>("NameOfUniversity");

                    b.Property<string>("Specialization");

                    b.Property<int>("Year");

                    b.HasKey("Id");

                    b.HasIndex("AccountId");

                    b.ToTable("Educations");
                });

            modelBuilder.Entity("questionnaire.Core.Domains.Experience", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int>("AccountId");

                    b.Property<string>("CompanyName");

                    b.Property<DateTime>("From");

                    b.Property<bool>("IsCurrentJob");

                    b.Property<string>("Location");

                    b.Property<string>("Position");

                    b.Property<DateTime>("To");

                    b.HasKey("Id");

                    b.HasIndex("AccountId");

                    b.ToTable("Experiences");
                });

            modelBuilder.Entity("questionnaire.Core.Domains.ImportFile.UnregisteredUser", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Course");

                    b.Property<DateTime>("DateOfCompletion");

                    b.Property<string>("Email");

                    b.Property<string>("Name");

                    b.Property<string>("Role");

                    b.Property<string>("Surname");

                    b.Property<string>("TypeOfStudy");

                    b.HasKey("Id");

                    b.ToTable("UnregisteredUsers");
                });

            modelBuilder.Entity("questionnaire.Core.Domains.JobOffer", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("CompanyName");

                    b.Property<string>("ContactPerson");

                    b.Property<string>("Description");

                    b.Property<string>("Email");

                    b.Property<int?>("EmployerId");

                    b.Property<string>("JobType");

                    b.Property<string>("Location");

                    b.Property<string>("PhoneNumber");

                    b.Property<string>("Position");

                    b.Property<string>("WebsiteAddress");

                    b.HasKey("Id");

                    b.HasIndex("EmployerId");

                    b.ToTable("JobOffers");
                });

            modelBuilder.Entity("questionnaire.Core.Domains.Language", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int>("AccountId");

                    b.Property<string>("Name");

                    b.Property<string>("Proficiency");

                    b.HasKey("Id");

                    b.HasIndex("AccountId");

                    b.ToTable("Languages");
                });

            modelBuilder.Entity("questionnaire.Core.Domains.ProfileLink", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int>("AccountId");

                    b.Property<string>("Content");

                    b.HasKey("Id");

                    b.HasIndex("AccountId")
                        .IsUnique();

                    b.ToTable("ProfileLinks");
                });

            modelBuilder.Entity("questionnaire.Core.Domains.Skill", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int?>("AccountId");

                    b.Property<string>("Name");

                    b.HasKey("Id");

                    b.HasIndex("AccountId");

                    b.ToTable("Skills");
                });

            modelBuilder.Entity("questionnaire.Core.Domains.SurveyReport.DataSet", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Data");

                    b.Property<string>("Label");

                    b.Property<int>("QuestionReportId");

                    b.HasKey("Id");

                    b.HasIndex("QuestionReportId");

                    b.ToTable("DataSets");
                });

            modelBuilder.Entity("questionnaire.Core.Domains.SurveyReport.QuestionReport", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int>("AnswersNumber");

                    b.Property<string>("Content");

                    b.Property<string>("LabelsList");

                    b.Property<int>("QuestionPosition");

                    b.Property<string>("Select");

                    b.Property<int>("SurveyReportId");

                    b.HasKey("Id");

                    b.HasIndex("SurveyReportId");

                    b.ToTable("QuestionReports");
                });

            modelBuilder.Entity("questionnaire.Core.Domains.SurveyReport.SurveyReport", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int>("AnswersNumber");

                    b.Property<DateTime>("CreatedAt");

                    b.Property<int>("SurveyId");

                    b.Property<string>("SurveyTitle");

                    b.HasKey("Id");

                    b.ToTable("SurveyReports");
                });

            modelBuilder.Entity("questionnaire.Core.Domains.Surveys.ChoiceOption", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int>("FieldDataId");

                    b.Property<int>("OptionPosition");

                    b.Property<bool>("Value");

                    b.Property<string>("ViewValue");

                    b.HasKey("Id");

                    b.HasIndex("FieldDataId");

                    b.ToTable("ChoiceOptions");
                });

            modelBuilder.Entity("questionnaire.Core.Domains.Surveys.FieldData", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Input");

                    b.Property<string>("MaxLabel");

                    b.Property<int>("MaxValue");

                    b.Property<string>("MinLabel");

                    b.Property<int>("MinValue");

                    b.Property<int>("QuestionId");

                    b.HasKey("Id");

                    b.HasIndex("QuestionId");

                    b.ToTable("FieldData");
                });

            modelBuilder.Entity("questionnaire.Core.Domains.Surveys.Question", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Content");

                    b.Property<bool>("IsRequired");

                    b.Property<int>("QuestionPosition");

                    b.Property<string>("Select");

                    b.Property<int>("SurveyId");

                    b.HasKey("Id");

                    b.HasIndex("SurveyId");

                    b.ToTable("Questions");
                });

            modelBuilder.Entity("questionnaire.Core.Domains.Surveys.Row", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int>("FieldDataId");

                    b.Property<string>("Input");

                    b.Property<int>("RowPosition");

                    b.HasKey("Id");

                    b.HasIndex("FieldDataId");

                    b.ToTable("Rows");
                });

            modelBuilder.Entity("questionnaire.Core.Domains.Surveys.Survey", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<DateTime>("CreatedAt");

                    b.Property<string>("Title");

                    b.HasKey("Id");

                    b.ToTable("Surveys");
                });

            modelBuilder.Entity("questionnaire.Core.Domains.Surveys.SurveyUserIdentifier", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<bool>("Answered");

                    b.Property<int>("SurveyId");

                    b.Property<string>("UserEmailHash");

                    b.HasKey("Id");

                    b.ToTable("SurveyUserIdentifiers");
                });

            modelBuilder.Entity("questionnaire.Core.Domains.SurveysAnswers.ChoiceOptionAnswer", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int>("FieldDataAnswerId");

                    b.Property<int>("OptionPosition");

                    b.Property<bool>("Value");

                    b.Property<string>("ViewValue");

                    b.HasKey("Id");

                    b.HasIndex("FieldDataAnswerId");

                    b.ToTable("ChoiceOptionsAnswers");
                });

            modelBuilder.Entity("questionnaire.Core.Domains.SurveysAnswers.FieldDataAnswer", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Input");

                    b.Property<string>("MaxLabel");

                    b.Property<string>("MinLabel");

                    b.Property<int>("QuestionAnswerId");

                    b.HasKey("Id");

                    b.HasIndex("QuestionAnswerId");

                    b.ToTable("FieldDataAnswers");
                });

            modelBuilder.Entity("questionnaire.Core.Domains.SurveysAnswers.QuestionAnswer", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Content");

                    b.Property<bool>("IsRequired");

                    b.Property<int>("QuestionPosition");

                    b.Property<string>("Select");

                    b.Property<int>("SurveyAnswerId");

                    b.HasKey("Id");

                    b.HasIndex("SurveyAnswerId");

                    b.ToTable("QuestionsAnswers");
                });

            modelBuilder.Entity("questionnaire.Core.Domains.SurveysAnswers.RowAnswer", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int>("FieldDataAnswerId");

                    b.Property<string>("Input");

                    b.Property<int>("RowPosition");

                    b.HasKey("Id");

                    b.HasIndex("FieldDataAnswerId");

                    b.ToTable("RowAnswers");
                });

            modelBuilder.Entity("questionnaire.Core.Domains.SurveysAnswers.RowChoiceOptionAnswer", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int>("OptionPosition");

                    b.Property<int>("RowAnswerId");

                    b.Property<bool>("Value");

                    b.Property<string>("ViewValue");

                    b.HasKey("Id");

                    b.HasIndex("RowAnswerId");

                    b.ToTable("RowChoiceOptionsAnswers");
                });

            modelBuilder.Entity("questionnaire.Core.Domains.SurveysAnswers.SurveyAnswer", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<DateTime>("CreatedAt");

                    b.Property<int>("SurveyId");

                    b.Property<string>("SurveyTitle");

                    b.HasKey("Id");

                    b.ToTable("SurveyAnswers");
                });

            modelBuilder.Entity("questionnaire.Core.Domains.SurveyTemplates.ChoiceOptionTemplate", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int>("FieldDataTemplateId");

                    b.Property<int>("OptionPosition");

                    b.Property<bool>("Value");

                    b.Property<string>("ViewValue");

                    b.HasKey("Id");

                    b.HasIndex("FieldDataTemplateId");

                    b.ToTable("ChoiceOptionTemplates");
                });

            modelBuilder.Entity("questionnaire.Core.Domains.SurveyTemplates.FieldDataTemplate", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Input");

                    b.Property<string>("MaxLabel");

                    b.Property<int>("MaxValue");

                    b.Property<string>("MinLabel");

                    b.Property<int>("MinValue");

                    b.Property<int>("QuestionTemplateId");

                    b.HasKey("Id");

                    b.HasIndex("QuestionTemplateId");

                    b.ToTable("FieldDataTemplates");
                });

            modelBuilder.Entity("questionnaire.Core.Domains.SurveyTemplates.QuestionTemplate", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Content");

                    b.Property<bool>("IsRequired");

                    b.Property<int>("QuestionPosition");

                    b.Property<string>("Select");

                    b.Property<int>("SurveyTemplateId");

                    b.HasKey("Id");

                    b.HasIndex("SurveyTemplateId");

                    b.ToTable("QuestionTemplates");
                });

            modelBuilder.Entity("questionnaire.Core.Domains.SurveyTemplates.RowTemplate", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int>("FieldDataTemplateId");

                    b.Property<string>("Input");

                    b.Property<int>("RowPosition");

                    b.HasKey("Id");

                    b.HasIndex("FieldDataTemplateId");

                    b.ToTable("RowTemplates");
                });

            modelBuilder.Entity("questionnaire.Core.Domains.SurveyTemplates.SurveyTemplate", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<DateTime>("CreatedAt");

                    b.Property<string>("Title");

                    b.HasKey("Id");

                    b.ToTable("SurveyTemplates");
                });

            modelBuilder.Entity("questionnaire.Core.Domains.CareerOffice", b =>
                {
                    b.HasBaseType("questionnaire.Core.Domains.Abstract.Account");


                    b.ToTable("CareerOffice");

                    b.HasDiscriminator().HasValue("CareerOffice");
                });

            modelBuilder.Entity("questionnaire.Core.Domains.Employer", b =>
                {
                    b.HasBaseType("questionnaire.Core.Domains.Abstract.Account");

                    b.Property<string>("CompanyDescription");

                    b.Property<string>("CompanyName");

                    b.Property<string>("Location");

                    b.ToTable("Employer");

                    b.HasDiscriminator().HasValue("Employer");
                });

            modelBuilder.Entity("questionnaire.Core.Domains.Graduate", b =>
                {
                    b.HasBaseType("questionnaire.Core.Domains.Abstract.Account");


                    b.ToTable("Graduate");

                    b.HasDiscriminator().HasValue("Graduate");
                });

            modelBuilder.Entity("questionnaire.Core.Domains.Student", b =>
                {
                    b.HasBaseType("questionnaire.Core.Domains.Abstract.Account");

                    b.Property<string>("IndexNumber");

                    b.ToTable("Student");

                    b.HasDiscriminator().HasValue("Student");
                });

            modelBuilder.Entity("questionnaire.Core.Domains.AccountActivation", b =>
                {
                    b.HasOne("questionnaire.Core.Domains.Abstract.Account", "Account")
                        .WithOne("AccountActivation")
                        .HasForeignKey("questionnaire.Core.Domains.AccountActivation", "AccountId")
                        .OnDelete(DeleteBehavior.Cascade);
                });

            modelBuilder.Entity("questionnaire.Core.Domains.AccountRestoringPassword", b =>
                {
                    b.HasOne("questionnaire.Core.Domains.Abstract.Account", "Account")
                        .WithOne("AccountRestoringPassword")
                        .HasForeignKey("questionnaire.Core.Domains.AccountRestoringPassword", "AccountId")
                        .OnDelete(DeleteBehavior.Cascade);
                });

            modelBuilder.Entity("questionnaire.Core.Domains.Certificate", b =>
                {
                    b.HasOne("questionnaire.Core.Domains.Abstract.Account", "Account")
                        .WithMany("Certificates")
                        .HasForeignKey("AccountId")
                        .OnDelete(DeleteBehavior.Cascade);
                });

            modelBuilder.Entity("questionnaire.Core.Domains.Course", b =>
                {
                    b.HasOne("questionnaire.Core.Domains.Abstract.Account", "Account")
                        .WithMany("Courses")
                        .HasForeignKey("AccountId")
                        .OnDelete(DeleteBehavior.Cascade);
                });

            modelBuilder.Entity("questionnaire.Core.Domains.Education", b =>
                {
                    b.HasOne("questionnaire.Core.Domains.Abstract.Account", "Account")
                        .WithMany("Educations")
                        .HasForeignKey("AccountId")
                        .OnDelete(DeleteBehavior.Cascade);
                });

            modelBuilder.Entity("questionnaire.Core.Domains.Experience", b =>
                {
                    b.HasOne("questionnaire.Core.Domains.Abstract.Account", "Account")
                        .WithMany("Experiences")
                        .HasForeignKey("AccountId")
                        .OnDelete(DeleteBehavior.Cascade);
                });

            modelBuilder.Entity("questionnaire.Core.Domains.JobOffer", b =>
                {
                    b.HasOne("questionnaire.Core.Domains.Employer")
                        .WithMany("JobOffers")
                        .HasForeignKey("EmployerId");
                });

            modelBuilder.Entity("questionnaire.Core.Domains.Language", b =>
                {
                    b.HasOne("questionnaire.Core.Domains.Abstract.Account", "Account")
                        .WithMany("Languages")
                        .HasForeignKey("AccountId")
                        .OnDelete(DeleteBehavior.Cascade);
                });

            modelBuilder.Entity("questionnaire.Core.Domains.ProfileLink", b =>
                {
                    b.HasOne("questionnaire.Core.Domains.Abstract.Account", "Account")
                        .WithOne("ProfileLink")
                        .HasForeignKey("questionnaire.Core.Domains.ProfileLink", "AccountId")
                        .OnDelete(DeleteBehavior.Cascade);
                });

            modelBuilder.Entity("questionnaire.Core.Domains.Skill", b =>
                {
                    b.HasOne("questionnaire.Core.Domains.Abstract.Account")
                        .WithMany("Skills")
                        .HasForeignKey("AccountId");
                });

            modelBuilder.Entity("questionnaire.Core.Domains.SurveyReport.DataSet", b =>
                {
                    b.HasOne("questionnaire.Core.Domains.SurveyReport.QuestionReport", "QuestionReport")
                        .WithMany("DataSets")
                        .HasForeignKey("QuestionReportId")
                        .OnDelete(DeleteBehavior.Cascade);
                });

            modelBuilder.Entity("questionnaire.Core.Domains.SurveyReport.QuestionReport", b =>
                {
                    b.HasOne("questionnaire.Core.Domains.SurveyReport.SurveyReport", "SurveyReport")
                        .WithMany("QuestionsReports")
                        .HasForeignKey("SurveyReportId")
                        .OnDelete(DeleteBehavior.Cascade);
                });

            modelBuilder.Entity("questionnaire.Core.Domains.Surveys.ChoiceOption", b =>
                {
                    b.HasOne("questionnaire.Core.Domains.Surveys.FieldData", "FieldData")
                        .WithMany("ChoiceOptions")
                        .HasForeignKey("FieldDataId")
                        .OnDelete(DeleteBehavior.Cascade);
                });

            modelBuilder.Entity("questionnaire.Core.Domains.Surveys.FieldData", b =>
                {
                    b.HasOne("questionnaire.Core.Domains.Surveys.Question", "Question")
                        .WithMany("FieldData")
                        .HasForeignKey("QuestionId")
                        .OnDelete(DeleteBehavior.Cascade);
                });

            modelBuilder.Entity("questionnaire.Core.Domains.Surveys.Question", b =>
                {
                    b.HasOne("questionnaire.Core.Domains.Surveys.Survey", "Survey")
                        .WithMany("Questions")
                        .HasForeignKey("SurveyId")
                        .OnDelete(DeleteBehavior.Cascade);
                });

            modelBuilder.Entity("questionnaire.Core.Domains.Surveys.Row", b =>
                {
                    b.HasOne("questionnaire.Core.Domains.Surveys.FieldData", "FieldData")
                        .WithMany("Rows")
                        .HasForeignKey("FieldDataId")
                        .OnDelete(DeleteBehavior.Cascade);
                });

            modelBuilder.Entity("questionnaire.Core.Domains.SurveysAnswers.ChoiceOptionAnswer", b =>
                {
                    b.HasOne("questionnaire.Core.Domains.SurveysAnswers.FieldDataAnswer", "FieldDataAnswer")
                        .WithMany("ChoiceOptionAnswers")
                        .HasForeignKey("FieldDataAnswerId")
                        .OnDelete(DeleteBehavior.Restrict);
                });

            modelBuilder.Entity("questionnaire.Core.Domains.SurveysAnswers.FieldDataAnswer", b =>
                {
                    b.HasOne("questionnaire.Core.Domains.SurveysAnswers.QuestionAnswer", "QuestionAnswer")
                        .WithMany("FieldDataAnswers")
                        .HasForeignKey("QuestionAnswerId")
                        .OnDelete(DeleteBehavior.Cascade);
                });

            modelBuilder.Entity("questionnaire.Core.Domains.SurveysAnswers.QuestionAnswer", b =>
                {
                    b.HasOne("questionnaire.Core.Domains.SurveysAnswers.SurveyAnswer", "SurveyAnswer")
                        .WithMany("QuestionsAnswers")
                        .HasForeignKey("SurveyAnswerId")
                        .OnDelete(DeleteBehavior.Cascade);
                });

            modelBuilder.Entity("questionnaire.Core.Domains.SurveysAnswers.RowAnswer", b =>
                {
                    b.HasOne("questionnaire.Core.Domains.SurveysAnswers.FieldDataAnswer", "FieldDataAnswer")
                        .WithMany("RowsAnswers")
                        .HasForeignKey("FieldDataAnswerId")
                        .OnDelete(DeleteBehavior.Cascade);
                });

            modelBuilder.Entity("questionnaire.Core.Domains.SurveysAnswers.RowChoiceOptionAnswer", b =>
                {
                    b.HasOne("questionnaire.Core.Domains.SurveysAnswers.RowAnswer", "RowAnswer")
                        .WithMany("RowChoiceOptionAnswers")
                        .HasForeignKey("RowAnswerId")
                        .OnDelete(DeleteBehavior.Restrict);
                });

            modelBuilder.Entity("questionnaire.Core.Domains.SurveyTemplates.ChoiceOptionTemplate", b =>
                {
                    b.HasOne("questionnaire.Core.Domains.SurveyTemplates.FieldDataTemplate", "FieldDataTemplate")
                        .WithMany("ChoiceOptionTemplates")
                        .HasForeignKey("FieldDataTemplateId")
                        .OnDelete(DeleteBehavior.Cascade);
                });

            modelBuilder.Entity("questionnaire.Core.Domains.SurveyTemplates.FieldDataTemplate", b =>
                {
                    b.HasOne("questionnaire.Core.Domains.SurveyTemplates.QuestionTemplate", "QuestionTemplate")
                        .WithMany("FieldDataTemplates")
                        .HasForeignKey("QuestionTemplateId")
                        .OnDelete(DeleteBehavior.Cascade);
                });

            modelBuilder.Entity("questionnaire.Core.Domains.SurveyTemplates.QuestionTemplate", b =>
                {
                    b.HasOne("questionnaire.Core.Domains.SurveyTemplates.SurveyTemplate", "SurveyTemplate")
                        .WithMany("QuestionTemplates")
                        .HasForeignKey("SurveyTemplateId")
                        .OnDelete(DeleteBehavior.Cascade);
                });

            modelBuilder.Entity("questionnaire.Core.Domains.SurveyTemplates.RowTemplate", b =>
                {
                    b.HasOne("questionnaire.Core.Domains.SurveyTemplates.FieldDataTemplate", "FieldDataTemplate")
                        .WithMany("RowTemplates")
                        .HasForeignKey("FieldDataTemplateId")
                        .OnDelete(DeleteBehavior.Cascade);
                });
#pragma warning restore 612, 618
        }
    }
}
